---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[shoryuken::default]
    attributes:
      shoryuken:
        app_dir: /srv/www/myapp/current
        environment_variables:
          DERP: herp
